<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanchit-PC" ignored="0" name="Default test" tests="20" failures="3" timestamp="04 Feb 2019 03:05:29 GMT" time="128.746" errors="0">
  <testcase name="checkAddRecordButtonDisabled" time="0.046" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="checkAddRecordButtonVisibility" time="0.036" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="checkExportButtonDisabled" time="0.058" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="checkExportButtonVisibility" time="0.028" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validatePageHTMLTitle" time="0.008" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validatePageHeaderText" time="0.033" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateRowAlignment" time="0.046" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - The page rows are not aligned to the left (Horizontally) as their x-axis values do not match expected [151] but found [136]">
      <![CDATA[java.lang.AssertionError: Test Failed - The page rows are not aligned to the left (Horizontally) as their x-axis values do not match expected [151] but found [136]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.app.qa.test.ProjectDashboardTest.validateRowAlignment(ProjectDashboardTest.java:136)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateRowAlignment -->
  <testcase name="validateAccountingStatistics" time="1.575" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateAdministrationStatistics" time="0.748" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateMarketingStatistics" time="0.698" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateSalesStatistics" time="0.7" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateProductionStatistics" time="1.93" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateArchivedStatistics" time="0.811" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateNewStatistics" time="0.974" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateWorkingStatistics" time="1.788" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateDeliveredStatistics" time="0.764" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateStatusUpdateStatistics" time="0.626" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - Statistics are not getting updated on updating the status of a record! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed - Statistics are not getting updated on updating the status of a record! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.app.qa.test.ProjectDashboardTest.validateStatusUpdateStatistics(ProjectDashboardTest.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateStatusUpdateStatistics -->
  <testcase name="validateRecordUpdateSaveOnRefresh" time="2.29" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - The updates made to the record were not refelected after page refresh!">
      <![CDATA[java.lang.AssertionError: Test Failed - The updates made to the record were not refelected after page refresh!
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at com.app.qa.test.ProjectDashboardTest.validateRecordUpdateSaveOnRefresh(ProjectDashboardTest.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateRecordUpdateSaveOnRefresh -->
  <testcase name="validateFeedbackOnUpdate" time="0.773" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateBudgetFormatOnUpdate" time="1.142" classname="com.app.qa.test.ProjectDashboardTest"/>
</testsuite> <!-- Default test -->
